Api
alionser/TestApi pull request #1
Opened 2022-07-29 08:56 UTC by alionser

2022-07-29 16:23 UTC, ProgressiveArt requested changes

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Controllers/EmployeeController.cs
> +        [FromRoute] int id, //Можно ли параметры сразу к команде привязать?
Можно, но в данном случае не нужно. Объект команды создается для следования договоренности и для возможности расширения в будущем. Если в Объекте command появится больше одного свойства, то атрибут FromRoute сменится на FromBody

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Controllers/DepartmentController.cs
> +    public async Task<IActionResult> GetDepartments([FromServices] GetDepartmentsQueryHandler handler, //нужно ли действие для получения единственного Department
Сделай получение департамента аналогично Delete

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Controllers/DepartmentController.cs
> +        var command = new DeleteDepartmentCommand //TODO: Добавить DeleteDepartmentCommand?
Нет, пока параметр один и это Id делаем так

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Controllers/EmployeeController.cs
> +    public async Task<IActionResult> GetEmployees([FromServices] GetEmployeesQueryHandler handler, //нужно ли действие для получения единственного Employee
Да, см. коммент выше

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Data/DataContext.cs
> +                .HasPrecision(8, 2);
Думаю, что не стоит ограничивать по кол-ву хранимых в бд чисел = 8, там по умолчанию 18 и 2, если не применять HasPrecision

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Data/Entities/Department.cs
> +    [JsonIgnore]
Не н отправлять объект сущности клиенту, под каждый запрос, где это нужно, создавай модель результата. GetDepartmentResultModel и в модели указывай необходимые свойства

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/DepartmentHandlers/CreateDepartmentCommandHandler.cs
> +        return new JsonResult(department);
Соответственно везде где возвращается объект Department нужно заменить на соответствующий Result

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/DepartmentHandlers/GetDepartmentsQueryHandler.cs
> +            .Select(x => new
Аналогично модели Department из БД нужно делать модели под все, никаких анонимных

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/DeleteEmployeeCommandHandler.cs
> +            return new JsonResult($"Failed to find Employee with Id:{command.Id}");
В фигурные скобки

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/DepartmentHandlers/UpdateDepartmentCommandHandler.cs
> +        department.Name = command.Name.Trim();
Если Name придет как пустая строка или null, то получим непредвиденную ошибку

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/DeleteEmployeeCommandHandler.cs
> +    DeleteEmployeeCommandHandler : ICommandHandler<DeleteEmployeeCommand> //TODO: подумать над наслдованием, у всех хендлеров одинаковый конструтор
Что за перенос? если не влез коммент, то пиши над объявлением. Трудно представляю как я в интерфейс\абстрактный класс поместить конструктор другого класса

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/GetEmployeesQueryHandler.cs
> +            .ToArrayAsync(ct);
1. Тернарник не очень читаемо
2. Если несколько условий, то объединяй их && или ||

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/GetEmployeesQueryHandler.cs
> +        // var employees = await _dataContext.Employees.ToArrayAsync(ct);
Зачем коммент, если ниже тот же самый код, но с фильтрацией?

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/UpdateEmployeeCommandHandler.cs
> +        updatedEmployee.Name = command.Name.Trim(); //  может стоить добавить проверку свойств command на null?
ты сам написал то, что нужно сделать (=

2022-07-29 16:23 UTC, ProgressiveArt commented on src/TestAPI.Web/Migrations/20220728161223_FixEployeeSalary.cs
> +            migrationBuilder.AlterColumn<decimal>(
Лучше откатить предыдущую миграции и по новой создать. Не такое сильное изменение - повышение точности numeric поля, чтобы делать миграцию

2022-07-29 16:25 UTC, alionser commented on src/TestAPI.Web/Controllers/DepartmentController.cs
> +    public async Task<IActionResult> GetDepartments([FromServices] GetDepartmentsQueryHandler handler, //нужно ли действие для получения единственного Department
через параметр маршрута id же?

2022-07-30 05:45 UTC, ProgressiveArt commented on src/TestAPI.Web/Controllers/DepartmentController.cs
> +    public async Task<IActionResult> GetDepartments([FromServices] GetDepartmentsQueryHandler handler, //нужно ли действие для получения единственного Department
да

2022-08-04 17:08 UTC, alionser commented on src/TestAPI.Web/Controllers/EmployeeController.cs
> +        [FromRoute] int id, //Можно ли параметры сразу к команде привязать?
+

2022-08-06 18:29 UTC, ProgressiveArt approved these changes

2022-08-06 18:29 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/DeleteEmployeeCommandHandler.cs
> +    DeleteEmployeeCommandHandler : ICommandHandler<DeleteEmployeeCommand>
Лишний перенос

2022-08-06 18:29 UTC, ProgressiveArt commented on src/TestAPI.Web/Handlers/EmployeeHandlers/UpdateEmployeeCommandHandler.cs
> +public class UpdateEmployeeCommandHandler : ICommandHandler<UpdateEmployeeCommand>
Давай как и везде - sealed

2022-08-06 18:30 UTC, merged